dist: xenial
sudo: required
language: java
jdk:
  - openjdk8
  - openjdk11
services:
  - docker
before_install:
  - if [ $(java -version 2>&1 | sed -E -n 's/.* version "([0-9]*).*$/\1/p') -gt 1 ] ; then export JAVA_VERSION_BUILD=$(java -version 2>&1 | sed -E -n 's/.* version "([0-9]*).*$/\1/p'); export JAVA_VERSION=$JAVA_VERSION_BUILD; else export JAVA_VERSION_BUILD=$(java -version 2>&1 | sed -E -n 's/.* version "([0-9]*)\.([0-9])\.([0-9]).*$/\1.\2/p'); export JAVA_VERSION=$(java -version 2>&1 | sed -E -n 's/.* version "([0-9]*)\.([0-9])\.([0-9]).*$/\1.\2.\3/p'); fi;
  - "./.travis/install_yq.sh"
install:
  - mvn -q install -Dmaven.javadoc.skip=true -B -V
script:
  - "./.travis/build.sh"
cache:
  directories:
    - "$HOME/.m2"